services:
  pg:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=uns-db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  uns1:
    build: ./uns
    ports:
      - "8004:8003"
    depends_on:
      pg:
        condition: service_healthy

  uns2:
    build: ./uns
    ports:
      - "8005:8003"
    depends_on:
      pg:
        condition: service_healthy

  nginx:
    image: nginx:1.23.3-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - uns1
      - uns2
    ports:
      - 80:80

  ftn:
    build: 
      context: ./ftn
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    volumes:
      - mediafiles:/app/mediafiles
    depends_on:
      - nginx

  ftn-front:
    build: ./ftn-front
    ports:
      - "8080:8080"
    depends_on:
      - ftn
    stdin_open: true
    tty: true
    volumes:
      - /app/node_modules

volumes:
  mediafiles: