# Generated by Django 4.1.5 on 2023-01-25 13:51

from django.db import migrations, models
import ftn_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('ftn_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to=ftn_api.models.upload_to),
        ),
        migrations.AddField(
            model_name='student',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to=ftn_api.models.upload_to),
        ),
    ]
