name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build-uns:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_TOKEN }}
    - name: Build the Docker image
      run: docker build ./uns --file Dockerfile --tag ${{secrets.DOCKER_USER}}/uns:latest
    - name: Docker Push
      run: docker push ${{secrets.DOCKER_USER}}/uns:latest

  build-ftn:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_TOKEN }}
    - name: Build the Docker image
      run: docker build ./ftn --file Dockerfile --tag ${{secrets.DOCKER_USER}}/ftn:latest
    - name: Docker Push
      run: docker push ${{secrets.DOCKER_USER}}/ftn:latest
      
  build-ftn-front:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_TOKEN }}
    - name: Build the Docker image
      run: docker build ./ftn-front --file Dockerfile --tag ${{secrets.DOCKER_USER}}/ftn-front:latest
    - name: Docker Push
      run: docker push ${{secrets.DOCKER_USER}}/ftn-front:latest
